### ISSUE TITLE
17.9 MB

### ISSUE THREAD

**Issue by vadimlitvinenko87** [richiehowelll/CatLock#1]
Are you fck kidding us. This must be 100kb and not bigger.

**Comment by richiehowelll** [comment]
@vadimlitvinenko87 
First of all... calm down.

Second of all, the reason for the size is that the python interpreter and all of the imported libraries must be bundled in the binary. 

So you have two options if 17.9mb is too large for your system.
1. Download the source code and run it with your own installed python interpreter
2. Build the exe yourself and use `UPX` to compress it - https://pyinstaller.org/en/v3.3/usage.html#using-upx
