### ISSUE TITLE
It's unclear how it works.

### ISSUE THREAD

**Issue by paolosezart** [richiehowelll/CatLock#2]
Why can't you lock the keyboard with the tray icon? Hotkeys are not the most convenient method of locking the keyboard.
If you are making a program for public access, you should probably think about several control options.

Although, maybe I just didn't understand how it works....

**Comment by richiehowelll** [comment]
Thanks for the suggestion, I will include this in the next release https://github.com/richiehowelll/cat-lock/commit/99acc3b6aa9d6116fe35525bbbac8744caa21b0c

**Comment by richiehowelll** [comment]
@paolosezart you can now lock the keyboard using the tray menu in [v1.1.0 ](https://github.com/richiehowelll/cat-lock/releases/tag/v1.1.0)
